name: CI Workflow & Docker Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        pip install mlflow pandas numpy scikit-learn matplotlib seaborn

    - name: Run MLflow Project (Training Local)
      working-directory: ./MLProject
      run: |
        python modelling.py
        # Pindahkan run_id ke root
        if [ -f "run_id.txt" ]; then mv run_id.txt ../run_id.txt; fi

    - name: Save Artifacts to GitHub (Commit mlruns)
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Tambahkan file baru
        git add MLProject/mlruns
        
        # Commit perubahan
        git commit -m "Auto-save: MLflow artifacts from CI" || echo "No changes to commit"
        
        # Pull untuk menghindari konflik
        git pull --rebase origin main
        
        # Push kembali ke repository
        git push origin main

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        # Baca Run ID
        if [ -f "run_id.txt" ]; then
          RUN_ID=$(cat run_id.txt)
          echo "Run ID: $RUN_ID"
        else
          echo "Error: run_id.txt not found."
          exit 1
        fi
        
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/loan-approval-model:latest"
        
      
        PWD=$(pwd)
        MODEL_URI="file://$PWD/MLProject/mlruns/0/$RUN_ID/artifacts/random_forest_model"
        
        echo "Building Docker image from: $MODEL_URI"
        
        mlflow models build-docker \
          --model-uri "$MODEL_URI" \
          --name "$IMAGE_NAME" \
          --enable-mlserver

        docker push "$IMAGE_NAME"