name: CI Workflow & Docker Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout Code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2. Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # 3. Install Dependencies
    - name: Install Dependencies
      run: |
        pip install mlflow dagshub pandas numpy scikit-learn matplotlib seaborn

    # 4. Run Training & Logging to DagsHub
    - name: Run MLflow Project (Training)
      working-directory: ./MLProject
      env:
        MLFLOW_TRACKING_URI: "https://dagshub.com/raflikamal/SMSML_M-Rafli-Kamal.mlflow"
        MLFLOW_TRACKING_USERNAME: "raflikamal"
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }} 
      run: python modelling.py

    # 5. Login ke Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 6. Build & Push Docker Image (Metode Python Helper)
    - name: Build and Push Docker Image
      env:
        MLFLOW_TRACKING_URI: "https://dagshub.com/raflikamal/SMSML_M-Rafli-Kamal.mlflow"
        MLFLOW_TRACKING_USERNAME: "raflikamal"
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        echo "Menjalankan script helper untuk mendapatkan Run ID..."
        
        # Jalankan script helper
        python get_run_id.py
        
        # Baca Run ID dari file yang dibuat script python
        if [ -f "run_id.txt" ]; then
          RUN_ID=$(cat run_id.txt)
          echo "Run ID ditemukan: $RUN_ID"
        else
          echo "Gagal: File run_id.txt tidak ditemukan. Cek log output script python di atas."
          exit 1
        fi
        
        # Nama Image
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/loan-approval-model:latest"
        
        echo "Building Docker image: $IMAGE_NAME using runs:/$RUN_ID/random_forest_model"
        
        # Build Docker
        mlflow models build-docker \
          --model-uri "runs:/$RUN_ID/random_forest_model" \
          --name "$IMAGE_NAME" \
          --enable-mlserver

        # Push ke Docker Hub
        echo "Pushing image to Docker Hub..."
        docker push "$IMAGE_NAME"